### ISSUE TITLE
Contact Form Gmail Auth: Server side authentication

### ISSUE THREAD

**Issue by dannydes** [dannydes/ecologie#65]
Blocks issue #46.

**Comment by dannydes** [comment]
Getting error: `` Uncaught Google_Service_Exception: { "error": { "errors": [ { "domain": "global", "reason": "required", "message": "Login Required", "locationType": "header", "location": "Authorization" } ], "code": 401, "message": "Login Required" } } ``

**Comment by dannydes** [comment]
`` Fatal error: Uncaught InvalidArgumentException: Invalid token format in C:\xampp\htdocs\wordpress\wp-content\themes\ecologie\vendor\google\apiclient\src\Google\Client.php:423 Stack trace: #0 C:\xampp\htdocs\wordpress\wp-content\themes\ecologie\includes\contact\gmail-auth.php(51): Google_Client->setAccessToken(Array) #1 C:\xampp\htdocs\wordpress\wp-includes\class-wp-hook.php(286): ecologie_get_access_token('') #2 C:\xampp\htdocs\wordpress\wp-includes\class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #3 C:\xampp\htdocs\wordpress\wp-includes\plugin.php(453): WP_Hook->do_action(Array) #4 C:\xampp\htdocs\wordpress\wp-admin\admin.php(156): do_action('admin_init') #5 C:\xampp\htdocs\wordpress\wp-admin\customize.php(13): require_once('C:\\xampp\\htdocs...') #6 {main} thrown in C:\xampp\htdocs\wordpress\wp-content\themes\ecologie\vendor\google\apiclient\src\Google\Client.php on line 423 ``

**Comment by dannydes** [comment]
``` php
array(2) { ["error"]=> string(13) "invalid_grant" ["error_description"]=> string(26) "Code was already redeemed." } 
```
